# Generated by Django 4.0.6 on 2023-01-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=200, verbose_name='비밀번호')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
